embeddings {
  tensor_name: "embedding:0"
  metadata_path: "/Users/iwatobipen/develop/py35env/testfolder/tensorflowtest/mollog/projector/metadata.tsv"
  sprite {
    image_path: "/Users/iwatobipen/develop/py35env/testfolder/tensorflowtest/mollog/mols.png"
    single_image_dim: 100
    single_image_dim: 100
  }
}
